# Generated by Django 4.2.3 on 2023-07-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
